### ISSUE TITLE
Typo in discrete estim

### ISSUE THREAD

**Issue by Joshua1989** [GAMPTeam/vampyre#6]
I found this when I used a discrete estimator for a complex valued PMF that is symmetric around 0, at the first iteration the estimator initialized the variance to be 0.
Actually, there should be an `abs` in this line
https://github.com/GAMPTeam/vampyre/blob/master/vampyre/estim/discrete.py#L65

**Comment by sdrangan** [comment]
Mengke,

Thanks for pointing this out!  I haven't tested any complex cases yet, so I
am sure you will find more problems like this.  I will correct this.

Sundeep

**Comment by sdrangan** [comment]
This has been corrected
